// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD51Nw6rgfznAJYk631sRUykiOTylyQO7I',
    appId: '1:168440958863:web:151f233175c07a5ffe45fa',
    messagingSenderId: '168440958863',
    projectId: 'campus-assistant-5d205',
    authDomain: 'campus-assistant-5d205.firebaseapp.com',
    storageBucket: 'campus-assistant-5d205.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDST7ub3DcQky3cpRg_k4_5rp_mCK9lnug',
    appId: '1:168440958863:android:070a3c1d32c0548afe45fa',
    messagingSenderId: '168440958863',
    projectId: 'campus-assistant-5d205',
    storageBucket: 'campus-assistant-5d205.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD51Nw6rgfznAJYk631sRUykiOTylyQO7I',
    appId: '1:168440958863:web:f007db6e94211e98fe45fa',
    messagingSenderId: '168440958863',
    projectId: 'campus-assistant-5d205',
    authDomain: 'campus-assistant-5d205.firebaseapp.com',
    storageBucket: 'campus-assistant-5d205.firebasestorage.app',
  );
}
